### ISSUE TITLE
Make aside section on group and course pages more available to mobile users

### ISSUE THREAD

**Issue by OssianEriksson** [fysikteknologsektionen/ftek-theme-v3#1]
The [fysikteknologsektionen/ftek-plugin](https://github.com/fysikteknologsektionen/ftek-plugin) WordPress plugin provides group and course pages which are styled in this theme. On these pages and their children there is an aside area for related pages and such. One suggestion is to have this area be more available to mobile users who right now have to scroll all the way to the bottom of the page in order to see it. This could for example be done by making the area stick to the top of the screen (like how [mtek](https://mtek.chalmers.se/mnollk/) does it) or by making it an expandable section with a button always visible on screen to view it.

**Comment by OssianEriksson** [comment]
Solved in [fysikteknologsektionen/ftek-plugin](https://github.com/fysikteknologsektionen/ftek-plugin) by [this commit](https://github.com/fysikteknologsektionen/ftek-plugin/commit/797426bd1dabb48e8be5adbeb89270a4cf72773d).

**Comment by ghost** [comment]
I haven't seen the end result, but fyi I would say it's more common to put the links below the main content but above the footer. Putting stuff that isn't the main content before the main content is usually bad,
